### ISSUE TITLE
Remove `ruby-sass` option from Theme Generator as it's no longer required for Windows

### ISSUE THREAD

**Issue by mwilliams2014** [liferay/liferay-themes-sdk#137] opened 2019-02-11 17:53 UTC
Building with `ruby-sass` enabled in the `package.json` causes the build to fail with the error shown in the community post
(Ruby Sass (after resolving the dependency) code block): [https://community.liferay.com/en_GB/forums/-/message_boards/message/110618170](https://community.liferay.com/en_GB/forums/-/message_boards/message/110618170)

It seems node-sass no longer requires Visual Studio, just node-gyp and Python to work, so ruby-sass is no longer needed. 
 
Note: that issue is present on 8.0.0-beta.5 up to the current version

**Comment by jbalsas** [comment] 2019-02-12 08:44
Hey @mwilliams2014, after setting `rubySass` to `true`, one should run `npm install --save-dev gulp-ruby-sass` to install the dependency.

Could you please check if that addresses the issue?

**Comment by mwilliams2014** [comment] 2019-02-12 14:55
Hey @jbalsas , yeah I installed and saved the dev dependency, but it still gave me this error.

**Comment by mwilliams2014** [comment] 2019-02-12 14:57
I'll give it another try to make sure

**Comment by mwilliams2014** [comment] 2019-02-12 15:09
Confirmed, it still logs the following errors:

```
[10:00:46] Using gulpfile ~\Desktop\projects\themes\7-1-themes\test-theme\gulpfile.js
[10:00:46] Starting 'build'...
[10:00:46] Starting 'build:clean'...
[10:00:48] Finished 'build:clean' after 1.09 s
[10:00:48] Starting 'build:base'...
[10:00:53] Finished 'build:base' after 5.38 s
[10:00:53] Starting 'build:src'...
[10:00:53] Finished 'build:src' after 14 ms
[10:00:53] Starting 'build:web-inf'...
[10:00:53] Finished 'build:web-inf' after 2.6 ms
[10:00:53] Starting 'build:liferay-look-and-feel'...
[10:00:53] Finished 'build:liferay-look-and-feel' after 18 ms
[10:00:53] Starting 'build:hook'...
[10:00:53] Finished 'build:hook' after 8.61 ms
[10:00:53] Starting 'build:themelets'...
[10:00:53] Starting 'build:themelet-src'...
[10:00:53] Finished 'build:themelet-src' after 1.04 ms
[10:00:53] Starting 'build:themelet-css-inject'...
[10:00:53] Starting 'build:themelet-js-inject'...
[10:00:53] gulp-inject Nothing to inject into _custom.scss.
[10:00:53] Finished 'build:themelet-css-inject' after 48 ms
[10:00:53] gulp-inject Nothing to inject into portal_normal.ftl.
[10:00:53] Finished 'build:themelet-js-inject' after 24 ms
[10:00:53] Finished 'build:themelets' after 78 ms
[10:00:53] Starting 'build:rename-css-dir'...
[10:00:53] Finished 'build:rename-css-dir' after 3.66 ms
[10:00:53] Starting 'build:compile-css'...
[10:00:53] Starting 'build:compile-ruby-sass'...
[10:00:54] error build/_css/clay/variables/_bs4-variable-overwrites.scss (Line 11: Invalid CSS after "...nput-margin-x: ": expected expression (e.g. 1px, bold), was "!default;")
[10:00:54] write ./\font_awesome.css
[10:00:55] error build/_css/clay/variables/_bs4-variable-overwrites.scss (Line 11: Invalid CSS after "...nput-margin-x: ": expected expression (e.g. 1px, bold), was "!default;")
[10:00:55] Finished 'build:compile-ruby-sass' after 1.65 s
[10:00:55] Finished 'build:compile-css' after 1.65 s
[10:00:55] Starting 'build:fix-url-functions'...
[10:00:55] Finished 'build:fix-url-functions' after 196 μs
[10:00:55] Starting 'build:move-compiled-css'...
[10:00:58] Finished 'build:move-compiled-css' after 2.85 s
[10:00:58] Starting 'build:remove-old-css-dir'...
[10:00:58] Finished 'build:remove-old-css-dir' after 336 ms
[10:00:58] Starting 'build:fix-at-directives'...
[10:00:58] Finished 'build:fix-at-directives' after 36 ms
[10:00:58] Starting 'build:r2'...
[10:00:58] Finished 'build:r2' after 86 ms
[10:00:58] Starting 'build:war'...
[10:00:58] Starting 'plugin:version'...
[10:00:58] Finished 'plugin:version' after 11 ms
[10:00:58] Starting 'plugin:war'...
[10:01:05] Finished 'plugin:war' after 6.49 s
[10:01:05] Finished 'build:war' after 6.51 s
[10:01:05] Finished 'build' after 18 s
```

**Comment by jbalsas** [comment] 2019-02-12 15:34
Hey @mwilliams2014, that seems to be a completely different error to the one pointed out at the forum. In there, the user is clearly missing installing the dependency and that's what the error message is signaling.

This showing looks like a problem with ruby sass and our source files, which is I thing a different problem.

@pat270, could you take a look at this?

**Comment by mwilliams2014** [comment] 2019-02-12 16:21
@jbalsas, it's the same error listed on the forums at the bottom in the Ruby Sass (after resolving the dependency): error log

**Comment by jbalsas** [comment] 2019-02-12 16:32
Got it, I missed that! I think it's an error on our css, then, probably nothing to fix here. @pat270, please confirm when you can! :)

**Comment by mwilliams2014** [comment] 2019-02-12 16:43
Ah, ok. Since ruby-sass is no longer required for Windows, I think the option can be removed. We also just removed this information from the documentation. Running with node-sass, without Visual Studio, works on Windows now, so the alternative is no longer required.

**Comment by pat270** [comment] 2019-02-12 18:14
@jbalsas @mwilliams2014 The Ruby Sass issue was fixed in https://github.com/liferay/clay/issues/1270 which was released with Clay 2.5.0. I'll answer the forum question.

**Comment by mwilliams2014** [comment] 2019-02-12 18:57
So this issue is fixed now, and will be fixed in the next release of the generator for freshly generated themes? I never used .sass files, just .scss files.

**Comment by pat270** [comment] 2019-02-12 19:40
It didn't seem like he was trying to parse `.sass` files from the post. Node Sass can parse `.sass` files you just need to pass a setting `indentedSyntax: true,`. 

I'm guessing you can pass it through `sassOptions` in `package.json` like so:
```
	"liferayTheme": {
		"baseTheme": "styled",
		"screenshot": "",
		"rubySass": false,
                "sassOptions": {
                     indentedSyntax: true,
                 },
		"templateLanguage": "ftl",
		"version": "7.1"
	},
```

I haven't tested it but there is some documentation at https://github.com/liferay/liferay-themes-sdk/tree/master/packages/liferay-theme-tasks#sassoptions.

**Comment by mwilliams2014** [comment] 2019-02-12 19:54
Setting ruby-sass to false and just using node-sass, with python and node-gyp installed, works for windows, so we don't need ruby-sass. At any rate, I can add this info to our reference docs perhaps.

**Comment by jbalsas** [comment] 2019-02-13 09:15
I think the problem is simply that we're still installing the old `unstyled` and `styled` versions from https://github.com/liferay/liferay-themes-sdk/blob/master/packages/liferay-theme-deps-7.1/package.json#L9-L10

**Closed** 2019-02-13 10:08 UTC
